'use strict';

// Generates src/data/sources.js from data/sources.json (which doubles as the
// runtime remote-update payload fetched by src/lib/remotesources.js).
// data/sources.json is the single source of truth for built-in presets; the
// generated module is committed because both the MV3 extension and the
// userscript build (manifest.json js list) need a plain JS file to
// concatenate. Zero dependencies.

const fs = require('fs');
const path = require('path');

const SOURCES_PATH = path.join('data', 'sources.json');
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const RULE_TYPES = ['multiplier', 'absolute', 'percentOff', 'formula', 'exclude'];

function isRule(r) {
  return r && typeof r === 'object' && RULE_TYPES.indexOf(r.type) !== -1
    && (r.type === 'exclude' || r.type === 'formula' || typeof r.value === 'number');
}

function isDate(v) {
  return v == null || DATE_RE.test(v);
}

function validateProfile(profile, where) {
  if (!profile || typeof profile !== 'object') throw new Error(where + ': not an object');
  if (typeof profile.id !== 'string' || !/^[a-z0-9][a-z0-9-]*$/.test(profile.id)) {
    throw new Error(where + ': missing/invalid id');
  }
  if (typeof profile.name !== 'string' || !profile.name) throw new Error(where + ': missing name');
  if (!isRule(profile.defaultRule)) throw new Error(where + ': invalid defaultRule');
  if (profile.rules && (typeof profile.rules !== 'object'
    || Object.values(profile.rules).some(r => !isRule(r)))) {
    throw new Error(where + ': invalid rules entry');
  }
  if (profile.nameIncludes && (!Array.isArray(profile.nameIncludes)
    || profile.nameIncludes.some(e => typeof e.match !== 'string' || !isRule(e.rule)))) {
    throw new Error(where + ': invalid nameIncludes entry');
  }
  if (profile.promos && (!Array.isArray(profile.promos)
    || profile.promos.some(p => !p || typeof p.match !== 'string' || !isRule(p.rule)
      || !isDate(p.startsAt) || !isDate(p.endsAt)
      || (p.reason != null && typeof p.reason !== 'string')))) {
    throw new Error(where + ': invalid promos entry');
  }
}

function loadSourceProfiles(repoRoot) {
  const doc = JSON.parse(fs.readFileSync(path.join(repoRoot, SOURCES_PATH), 'utf8'));
  if (!doc || doc.schema !== 1 || !Array.isArray(doc.sources)) {
    throw new Error(SOURCES_PATH + ': expected { "schema": 1, "sources": [...] }');
  }
  const seen = new Set();
  return doc.sources.map(profile => {
    validateProfile(profile, SOURCES_PATH + ' entry');
    if (seen.has(profile.id)) throw new Error(SOURCES_PATH + ': duplicate source id: ' + profile.id);
    seen.add(profile.id);
    // Everything in data/sources.json is a built-in preset; the flag is
    // injected here so the JSON stays pure pricing data.
    profile.builtin = true;
    return profile;
  });
}

function buildSourcesModule(repoRoot) {
  const profiles = loadSourceProfiles(repoRoot);
  const body = profiles
    .map(p => '    ' + JSON.stringify(p, null, 2).replace(/\n/g, '\n    '))
    .join(',\n');

  return [
    '// GENERATED by scripts/build-sources.js from data/sources.json - do not edit by hand.',
    '// Regenerate with: node scripts/build-sources.js',
    "(function (root) {",
    "  'use strict';",
    "  root.RepriceAA = root.RepriceAA || {};",
    '  root.RepriceAA.SOURCES = [',
    body,
    '  ];',
    '})(typeof window !== \'undefined\' ? window : globalThis);',
    ''
  ].join('\n');
}

module.exports = { buildSourcesModule, loadSourceProfiles };

if (require.main === module) {
  const root = path.join(__dirname, '..');
  const outPath = path.join(root, 'src', 'data', 'sources.js');
  const code = buildSourcesModule(root);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, code);
  console.log('wrote ' + path.relative(root, outPath) + ' (' + code.length + ' bytes)');
}
